all:
  hosts:
    node1:
      ansible_host: 35.246.32.169
      ip: 10.240.0.4
    node2:
      ansible_host: 35.246.0.117
      ip: 10.240.0.7
    node3:
      ansible_host: 34.105.250.30
      ip: 10.240.0.8
    node4:
      ansible_host: 35.197.255.251
      ip: 10.240.0.5
    node5:
      ansible_host: 35.230.144.123
      ip: 10.240.0.2
    node6:
      ansible_host: 35.197.238.106
      ip: 10.240.0.3
    node7:
      ansible_host: 34.105.205.216
      ip: 10.240.0.6
    node8:
      ansible_host: 35.189.76.39
      ip: 10.240.0.9
  children:
    kube-master:
      hosts:
        node2:
        node5:
        node7:
    kube-node:
      hosts:
        node1:
        node3:
        node6:
        node8:
    kube-ingress:
        node1:
        node4:
    etcd:
      hosts:
        node2:
        node5:
        node7:
    k8s-cluster:
      children:
        kube-master:
        kube-node:
    calico-rr:
      hosts: {}
